py_library(
    name = "patients",
    srcs = [
        "__init__.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//services/example_fast_api/src/domain/patients/definitions",
        "//services/example_fast_api/src/domain/patients/use_cases",
    ],
)
