py_library(
    name = "src",
    srcs = [
        "__init__.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//services/example_fast_api/src/domain",
        "//services/example_fast_api/src/infra",
        "//services/example_fast_api/src/service",
    ],
)
