py_library(
    name = "infra",
    srcs = [
        "__init__.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)

test_suite(
    name = "test_unit",
    tests = [
        "//services/example_fast_api/src/infra/patients:test_unit",
    ],
)
